import { VerticalBox , HorizontalBox, GroupBox, StandardTableView, ProgressIndicator, Button} from "std-widgets.slint";


export global TableViewPageAdapter  {
    in property <[[StandardListViewItem]]> row_data: [
        [ { text: "Item 1.1" }, { text: "Item 1.2" }, { text: "Item 1.3" }, { text: "Item 1.4" }, ],
        [ { text: "Item 2.1" }, { text: "Item 2.2" }, { text: "Item 2.3" }, { text: "Item 2.4" }, ],
        [ { text: "Item 3.1" }, { text: "Item 3.2" }, { text: "Item 3.3" }, { text: "Item 3.4" }, ],
        [ { text: "Item 4.1" }, { text: "Item 4.2" }, { text: "Item 4.3" }, { text: "Item 4.4" }, ],
        [ { text: "Item 5.1" }, { text: "Item 5.2" }, { text: "Item 5.3" }, { text: "Item 5.4" }, ],
        [ { text: "Item 6.1" }, { text: "Item 6.2" }, { text: "Item 6.3" }, { text: "Item 6.4" }, ],
    ];

    callback sort_ascending(int);
    callback sort_descending(int);
}

export component AppWindow inherits Window {
  title: @tr("Tutti: Music Player");

  VerticalBox {

        GroupBox {
            title: @tr("Song List");

            StandardTableView {
                sort-ascending(index) => {
                    TableViewPageAdapter.sort_ascending(index);
                }

                sort-descending(index) => {
                    TableViewPageAdapter.sort-descending(index);
                }

                columns: [
                    { title: @tr("Song") },
                    { title: @tr("Artist") },
                    { title: @tr("Album") },
                    { title: @tr("Duration") },
                ];
                rows: TableViewPageAdapter.row_data;
            }
        }
    }

    VerticalBox {

      GroupBox {
        title: @tr("Now Listening To...");

        Image {
          source: @image-url("assets/ottr.png");
        }

        HorizontalBox {
          horizontal-stretch: 1;
          vertical-stretch: 0;

          Text {
            text: "0:00";
          }

          ProgressIndicator {
            progress: 0.5;
          }

          Text {
            text:"2:45";
          }
        }

        HorizontalBox {

          Button {
            icon: @image-url("assets/Skip_Backward.svg");
          }

          Button {
            icon: @image-url("assets/Skip_Backward.svg");
          }

          Button {
            icon: @image-url("assets/Skip_Backward.svg");
          }
        }

      }
    }
}
